development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: THP_POS_devlopment
  pool: 5
  username: walid
  password: walid
test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: THP_POS_test
  pool: 5
  username: walid
  password: walid
production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: THP_POS_production
  pool: 5
  username: walid
  password: walid